### ISSUE TITLE
Delete incorrect release 0.1.6 from PyPI

### ISSUE THREAD

**Issue by 5A11** [polkascan/py-sr25519-bindings#12]
There is a 0.1.6 release on PyPI which seems to be a mistake (released at the same time as 0.2.0 and there is no 0.1.6 release on Github). Can you please delete it on PyPI so downstream software stops breaking?

**Comment by arjanz** [comment]
Deleted, was indeed a mistake and must have been an artifact somehow in the wheels folder while uploading 0.2.0.
