### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by mxft** [polkascan/py-sr25519-bindings#13]
Package can't be installed using just `pip install py-sr25519-bindings` on Python 3.11 and Python 3.11.1. 

```
Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
     
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by arjanz** [comment]
There are indeed no Python 3.11 wheels available yet (https://pypi.org/project/py-sr25519-bindings/#files), so it resorts to compiling from source (and failing because you don't have a RUST toolchain installed). 

I will make a todo to try again to add the Python 3.11 wheels (I remember there were some dependency issues). For the time if you are able to use Python 3.10 then there should a wheel available for your arch.

**Comment by arjanz** [comment]
There are Python 3.11 wheels available (https://pypi.org/project/py-sr25519-bindings/#files), but somehow can't find a wheel for your os/arch so it resorts to compiling from source (and failing because you don't have a RUST toolchain installed). 

What is your OS/arch?

**Comment by mxft** [comment]
My OS is Windows 10 22H2 (19045.2486)

**Comment by arjanz** [comment]
Ok I will try to find a Windows runner to build the 3.11 wheels

**Comment by mxft** [comment]
I would be very grateful!

**Comment by arjanz** [comment]
Ok added win64 wheel, is it working for you now?

**Comment by mxft** [comment]
Works perfectly now! Thank you for your quick solution.
