### ISSUE TITLE
Include Cargo.lock in repo

### ISSUE THREAD

**Issue by dotlambda** [polkascan/py-sr25519-bindings#14]
That would make it easier for distributions to package py-sr25519-bindings.
See also https://github.com/rust-lang/cargo/issues/315.

**Comment by arjanz** [comment]
But what I read in the link you provided is that Cargo.lock should not be included for libraries? (https://github.com/rust-lang/cargo/issues/315#issuecomment-51075730)

Rust docs also state the same: https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

**Comment by dotlambda** [comment]
> But what I read in the link you provided is that Cargo.lock should not be included for libraries?

Yes, it shouldn't be included for *Rust* libraries.
Your Python library however is at the end of the Rust dependency chain.
