### ISSUE TITLE
Missing functions: MuSig, pubkey.decompress and compress

### ISSUE THREAD

**Issue by parizad1188** [polkascan/py-sr25519-bindings#3]
Hi,
Thanks for the schnorrkel python bindings.

It would be very helpful if you could provide multi-sig functionality plus compress/decompress for Pubkey.

**Comment by parizad1188** [comment]
We added two functions to address this issue, You can find our fork below:
[multi_sig_fork](https://github.com/aghamir/py-sr25519-bindings)

**Comment by arjanz** [comment]
Sorry for the late reply, time has been limited lately. 

I checked the changes you made and would like to integrate these functions soon, would make a great addition.
