### ISSUE TITLE
Generate wheel for aarch64

### ISSUE THREAD

**Issue by yabirgb** [polkascan/py-sr25519-bindings#4]
Hello! We at https://github.com/rotki are preparing a version of our app for `aarch64` and would be nice if this project could also provided wheel files for this architecture at pypi.

I saw that you already have a github action to build in different platforms so maybe could be useful to use this project https://github.com/uraimo/run-on-arch-action

Thank you

**Comment by arjanz** [comment]
Better late than never, latest release https://pypi.org/project/py-sr25519-bindings/0.1.4/ provides `aarch64` wheels

**Comment by yabirgb** [comment]
@arjanz Thank you very much for your work! Will be very useful :)
